base_log_dir: "logs"

data:
  dataset_path: "datasets/fsd"
  init_sources:
    - "real"  # 0
    - "stylegan-"  # 1
    - "stylegan2"  # 2
    - "stylegan3"  # 3
  emerging_sources:
    - "progan"  # 4
    - "dalle3"  # 5
    - "mjv6"  # 6
    - "firefly"  # 7
    - "sd14"  # 8
    - "sd3"  # 9
    # - "eg3d"  # 10
    # - "sd2"  # 11
    - "mjv5" # 12
    - "sdxl" # 13
  ood_sources:
    - "tam_trans" # 9
  test_size: 0.2
  seed: 42

training_kwargs:
  num_epochs: 20
  alpha: 1.0
  beta: 0.5
  batch_size: 64
  lr: 1e-4
  ft_lr_factor: 1.0
  pl_patience: 0
  es_patience: 3
  weight_decay: 1e-2
  top_k: 3
  device: "cuda"
  n_components: 5
  cov_type: "full"
  is_bayesian: true
  cluster_min_samples: 7

num_trials: 10
v_threshold: 10000.0
size_threshold: 75
size_adaptive_coeff: 1.1

random_seed: 42
use_autoencoder: true
do_nothing: false
do_retrain: false
refine_factor: 1.0
max_ood_fpr: 0.05
min_ood_tpr: 0.10
