base_log_dir: "logs"

data:
  dataset_path: "datasets/fsd"
  init_sources:
    - "real"  # 0
    - "stylegan-"  # 1
    - "stylegan2"  # 2
    - "stylegan3"  # 3
  emerging_sources:
    - "progan"  # 4
    - "dalle3"  # 5
    - "mjv6"  # 6
    - "firefly"  # 7
    - "sd3"  # 8
  ood_sources:
    - "tam_trans"  # 9

  test_size: 0.2
  seed: 42


v_threshold: 0.7
size_threshold: 150
size_adaptive_coeff: 1.1
num_trials: 7

training_kwargs:
  num_epochs: 15
  alpha: 1.0
  beta: 0.5
  batch_size: 64
  lr: 1e-4
  ft_lr_factor: 1.0
  pl_patience: 0
  es_patience: 5
  weight_decay: 1e-2
  top_k: 3
  device: "cuda"
  n_components: 5
  cov_type: "full"
  is_bayesian: false

random_seed: 42
use_autoencoder: true
do_nothing: false
do_retrain: false
refine_factor: 1.0
max_ood_fpr: 0.05
min_ood_tpr: 0.10
