base_log_dir: "logs_solo"

data:
  dataset_path: "datasets/fsd"
  init_sources:
    - "real-in1k-2000"  # 0
    - "stylegan3-2000"  # 3
    - "stylegan2-2000"  # 2
    - "stylegan-2000"  # 1
  emerging_sources:
    # - "progan"  # 4
    # - "dalle3"  # 5
    # - "mjv6"  # 6
    # - "firefly"  # 7
    # - "sd14"  # 8
    # - "sd15"  # 9
    # - "sd3"  # 10
    - "sdxl" # 11
  ood_sources:
    - "tam_trans" # 9
  test_size: 0.2
  seed: 42

training_kwargs:
  num_epochs: 50
  alpha: 1.0
  beta: 1.0
  batch_size: 256
  lr: 1e-4
  ft_lr_factor: 1.0
  pl_patience: 0
  es_patience: 3
  weight_decay: 1e-2
  top_k: 64
  device: "cuda"
  n_components: 5
  cov_type: "spherical"
  is_bayesian: true
  cluster_min_samples: 7

num_trials: 10
v_threshold: 10000.0
size_threshold: 75
size_adaptive_coeff: 1.1

random_seed: 42
use_autoencoder: true
do_nothing: false
is_solo: false
do_retrain: false
refine_factor: 1.0
max_ood_fpr: 0.05
min_ood_tpr: 0.10
